name: 'build'
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - uses: actions/checkout@v1
    - run: python -m pip install -r docs/requirements.txt
    - name: Build theme
      run: |
        yarn
        yarn build
    - uses: actions/upload-artifact@master
      with:
        name: btd.sphinx.theme
        path: dist