name: 'doc'

on: [push, pull_request]

jobs:

  btd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        npm ci
        npm run build
    - run: ./release.sh
      env:
        GIT_ORIGIN: https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
    - run: cp -r sphinx_btd_theme docs/_theme
    - uses: buildthedocs/btd@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
